version: "3.9"
services:
  address-table-server-frontend:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4001:4001"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - /app/node_modules
      - /app/build
      - ./client:/app
    networks:
      - address-table-server-network
    depends_on:
      - address-table-server-backend

  address-table-server-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - ADMIN_PASSWORD=something
        - DATABASE=address-table-server
        - MONGO_URI=mongodb://address-table-server-mongodb:27017
        - RABBIT_MQ=amqp://stage:12345@xcodeclazz-mq-backend-stage:5672
    restart: always
    ports:
      - "8081:8081"
    environment:
      - JWT_KEY=something
      - PORT=8081
    volumes:
      - /app/node_modules
      - /app/dist
      - .:/app
    networks:
      - message-queue-network
      - address-table-server-network
    depends_on:
      - address-table-server-mongodb

  address-table-server-mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - address-table-server-mongodb:/data/db/address-table-server
    ports:
      - "27011:27017"
    networks:
      - address-table-server-network

networks:
  address-table-server-network:
    external: true
  message-queue-network:
    external: true

volumes:
  address-table-server-mongodb: