version: '3.8'
services:
  bundle:
    build:
      dockerfile: Dockerfile.prod
      context: .
      args:
        - NODE_ENV=production
        - ADMIN_PASSWORD=something
        - MONGO_URI=mongodb://mongodb:27017
        - DATABASE=address-table-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=something
      - PORT=8080
    volumes:
      - /app/client/node_modules
      - /app/node_modules
      - /app/client/build
      - /app/dist
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    hostname: mongodb
    restart: unless-stopped
    volumes:
      - address-table-server:/data/db/address-table-server
    ports:
      - "27017:27017"

volumes:
  address-table-server: