version: '3.9'
services:
  address-table-server-frontend:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - /app/node_modules
      - /app/build
      - ./client:/app
    depends_on:
      - address-table-server-backend

  address-table-server-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - ADMIN_PASSWORD=something
        - DATABASE=address-table-server
        - RABBIT_MQ=amqp://appname:password@localhost:port
        - MONGO_URI=mongodb://address-table-server-mongodb:27017
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=something
      - PORT=8080
    volumes:
      - /app/node_modules
      - /app/dist
      - .:/app
    depends_on:
      - address-table-server-mongodb

  address-table-server-mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - address-table-server-mongodb:/data/db/address-table-server
    ports:
      - "27017:27017"

volumes:
  address-table-server-mongodb: