version: '3.8'
services:
  address-table-server:
    build:
      dockerfile: Dockerfile.prod
      context: .
      args:
        - NODE_ENV=production
        - ADMIN_PASSWORD=something
        - MONGO_URI=mongodb://mongodb:27017
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE=address-table-server
      - JWT_KEY=something
      - PORT=3000
    volumes:
      - /app/node_modules
      - /app/dist
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    hostname: mongodb
    restart: unless-stopped
    volumes:
      - address-table-server:/data/db/address-table-server
    ports:
      - "27017:27017"

volumes:
  address-table-server: