version: "3.9"
services:
  address-table-server-backend-production:
    image: yevdokiyaalex/address-table-server-production # PASSWORD REQUIRED
    restart: always
    ports:
      - "8081:8081"
    environment:
      - JWT_KEY=ydO4VUkf5eAJ4aub97zhaD8Vm3pPFOC9TTLt528R
      - PORT=8081