version: '3.9'
services:
  address-table-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - /app/dist
      - .:/app